# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy - captivlink-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: captivlink-ui
  BACKEND_IMAGE_NAME: captivlink-backend
  API_IMAGE_NAME: captivlink-api
  TAG: ${{ github.sha }}
  
jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
          
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

    - name: Install dependencies
      run: dotnet restore Captivlink.Api/Captivlink.Api.csproj
    
    - name: Build
      run: dotnet build Captivlink.Api/Captivlink.Api.csproj -c Release -o ./backend/deploy

    - name: Publish
      run: dotnet publish Captivlink.Api/Captivlink.Api.csproj -c Release -o ./backend/deploy

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Captivlink.Api/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/captivlink/${{ env.BACKEND_IMAGE_NAME }}:${{ env.TAG }}

  deploy-backend:
    runs-on: ubuntu-latest
    needs: [build-backend]
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'captivlink-backend'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8479942D205E4AD5948A94F89CA7F340 }}
        images: ${{ env.REGISTRY }}/captivlink/${{ env.BACKEND_IMAGE_NAME }}:${{ env.TAG }}
